import React from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useAuth } from "../../core/auth/AuthContext";
import { fetchSpendingSummary, fetchSpendingTransactions, type SpendingPeriod, type SpendingSummary, type SpendingTransaction } from "../../core/pricing/spendingApi";

const C={bg:"#090B10",card:"#12151B",card2:"#171A21",border:"rgba(255,255,255,.10)",text:"#FFFFFF",soft:"rgba(255,255,255,.62)",gold:"#D2B07A",green:"#88D7A6",red:"#FF9CA8",blue:"#93B9E8"};
function money(value:any,currency="USD"){const n=Number(value||0);try{return new Intl.NumberFormat("en-US",{style:"currency",currency:currency==="MIXED"?"USD":currency||"USD",minimumFractionDigits:2}).format(n)+(currency==="MIXED"?"+":"")}catch{return `${currency} ${n.toFixed(2)}`}}
function signedCredits(value:any){if(value===null||value===undefined)return "—";const n=Number(value||0);return `${n>0?"+":""}${Math.round(n).toLocaleString()}`}
function dateLabel(value:string){try{return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"2-digit"}).format(new Date(value))}catch{return value}}
function periodLabel(p:SpendingPeriod){return p==="yoy"?"YoY":p[0].toUpperCase()+p.slice(1)}

export default function SpendingHistoryScreen(){
  const auth=useAuth() as any;const token=String(auth?.token||"");const insets=useSafeAreaInsets();
  const[period,setPeriod]=React.useState<SpendingPeriod>("month");const[filter,setFilter]=React.useState("all");const[summary,setSummary]=React.useState<SpendingSummary|null>(null);const[items,setItems]=React.useState<SpendingTransaction[]>([]);const[loading,setLoading]=React.useState(true);const[error,setError]=React.useState("");
  const load=React.useCallback(async()=>{if(!token)return;setLoading(true);setError("");try{const[s,t]=await Promise.all([fetchSpendingSummary(token,period),fetchSpendingTransactions(token,period,filter,100,0)]);setSummary(s);setItems(Array.isArray(t.items)?t.items:[])}catch(e:any){setError(String(e?.message||"Unable to load spending history"))}finally{setLoading(false)}},[token,period,filter]);
  React.useEffect(()=>{void load()},[load]);
  const currency=summary?.money?.currency||"USD";const top=summary?.top_category;
  return <View style={[styles.root,{paddingTop:insets.top}]}><View style={styles.header}><Pressable onPress={()=>router.back()} style={styles.back}><Text style={styles.backText}>‹</Text></Pressable><View style={{flex:1}}><Text style={styles.kicker}>PLAN & BILLING</Text><Text style={styles.title}>Spending & transactions</Text></View></View><ScrollView contentContainerStyle={[styles.content,{paddingBottom:Math.max(insets.bottom,20)+28}]} showsVerticalScrollIndicator={false}>
    <Text style={styles.intro}>See money actually paid, credits purchased and credits consumed. Usage is never presented as a cash payment.</Text>
    <View style={styles.pills}>{(["month","quarter","year","yoy"] as SpendingPeriod[]).map(p=><Pressable key={p} onPress={()=>setPeriod(p)} style={[styles.pill,period===p&&styles.pillActive]}><Text style={[styles.pillText,period===p&&styles.pillTextActive]}>{periodLabel(p)}</Text></Pressable>)}</View>
    {loading&&!summary?<ActivityIndicator style={{marginTop:28}} color={C.gold}/>:error&&!summary?<Pressable style={styles.error} onPress={()=>void load()}><Text style={styles.errorText}>{error} · Tap to retry</Text></Pressable>:summary?<>
      <View style={styles.kpiGrid}><View style={styles.kpi}><Text style={styles.kpiLabel}>Credits used</Text><Text style={styles.kpiValue}>{Math.round(summary.credits.consumed).toLocaleString()}</Text><Text style={styles.kpiMeta}>{summary.comparison.credits_consumed_delta_percent==null?"No prior comparison":`${summary.comparison.credits_consumed_delta_percent>0?"↑":"↓"} ${Math.abs(summary.comparison.credits_consumed_delta_percent).toFixed(1)}% vs prior`}</Text></View><View style={styles.kpi}><Text style={styles.kpiLabel}>Money paid</Text><Text style={styles.kpiValue}>{money(summary.money.paid,currency)}</Text><Text style={styles.kpiMeta}>Actual recorded payments</Text></View><View style={styles.kpi}><Text style={styles.kpiLabel}>Credits purchased</Text><Text style={styles.kpiValue}>{Math.round(summary.credits.purchased).toLocaleString()}</Text><Text style={styles.kpiMeta}>{money(summary.money.credit_purchases,currency)} top-ups</Text></View><View style={styles.kpi}><Text style={styles.kpiLabel}>Available</Text><Text style={styles.kpiValue}>{Math.round(summary.credits.available).toLocaleString()}</Text><Text style={styles.kpiMeta}>{Math.round(summary.credits.reserved).toLocaleString()} reserved</Text></View></View>
      <View style={styles.card}><View style={styles.cardHead}><Text style={styles.cardTitle}>Where your credits went</Text><Text style={styles.cardMeta}>{top?`${top.category} leads`:"No usage yet"}</Text></View>{summary.categories.length?summary.categories.slice(0,6).map((c,i)=><View key={c.category} style={styles.categoryRow}><View style={styles.categoryTop}><Text style={styles.categoryName}>{c.category}</Text><Text style={styles.categoryValue}>{Math.round(c.credits).toLocaleString()} · {c.percent.toFixed(1)}%</Text></View><View style={styles.bar}><View style={[styles.fill,{width:`${Math.max(0,Math.min(100,c.percent))}%`,backgroundColor:i===0?C.gold:C.blue}]}/></View></View>):<Text style={styles.empty}>No completed usage in this period.</Text>}</View>
      <View style={styles.card}><Text style={styles.cardTitle}>Money paid breakdown</Text><View style={styles.moneyRow}><Text>Credit packs</Text><Text>{money(summary.money.credit_purchases,currency)}</Text></View><View style={styles.moneyRow}><Text>Subscriptions</Text><Text>{money(summary.money.subscriptions,currency)}</Text></View>{Number(summary.money.invoices||0)>0&&<View style={styles.moneyRow}><Text>Invoices</Text><Text>{money(summary.money.invoices,currency)}</Text></View>}{Number(summary.money.refunds||0)>0&&<View style={styles.moneyRow}><Text>Refunds</Text><Text>{money(summary.money.refunds,currency)}</Text></View>}<Text style={styles.note}>{summary.money.note}</Text></View>
    </>:null}
    <View style={styles.sectionHead}><View><Text style={styles.kicker}>TRANSACTION HISTORY</Text><Text style={styles.sectionTitle}>Purchases & usage</Text></View></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.pills}>{["all","usage","purchase","subscription","refund"].map(x=><Pressable key={x} onPress={()=>setFilter(x)} style={[styles.pill,filter===x&&styles.pillActive]}><Text style={[styles.pillText,filter===x&&styles.pillTextActive]}>{x[0].toUpperCase()+x.slice(1)}</Text></Pressable>)}</ScrollView>
    <View style={styles.card}>{items.length?items.map(tx=><View style={styles.tx} key={tx.id}><View style={{flex:1}}><Text style={styles.txTitle}>{tx.category||tx.label}</Text><Text style={styles.txMeta}>{dateLabel(tx.occurred_at)} · {tx.type.replaceAll("_"," ")} · {tx.status}</Text></View><View style={styles.txAmounts}><Text style={[styles.txCredits,Number(tx.credits||0)>0&&{color:C.green}]}>{signedCredits(tx.credits)}</Text><Text style={styles.txMoney}>{tx.money==null?"":money(tx.money,tx.currency||currency)}</Text></View></View>):!loading?<Text style={styles.empty}>No matching transactions in this period.</Text>:null}</View>
  </ScrollView></View>
}

const styles=StyleSheet.create({root:{flex:1,backgroundColor:C.bg},header:{height:70,paddingHorizontal:16,flexDirection:"row",alignItems:"center",gap:12,borderBottomWidth:1,borderBottomColor:C.border},back:{width:36,height:36,borderRadius:12,borderWidth:1,borderColor:C.border,alignItems:"center",justifyContent:"center"},backText:{color:C.text,fontSize:28,lineHeight:30},kicker:{fontSize:9,fontWeight:"900",letterSpacing:1.2,color:C.gold},title:{fontSize:20,fontWeight:"900",color:C.text,marginTop:2},content:{padding:16},intro:{color:C.soft,fontSize:12,lineHeight:18},pills:{gap:7,paddingVertical:12},pill:{paddingHorizontal:12,paddingVertical:8,borderRadius:999,borderWidth:1,borderColor:C.border,backgroundColor:C.card},pillActive:{borderColor:C.gold,backgroundColor:"rgba(210,176,122,.14)"},pillText:{color:C.soft,fontSize:11,fontWeight:"800"},pillTextActive:{color:C.gold},kpiGrid:{flexDirection:"row",flexWrap:"wrap",gap:10},kpi:{width:"48%",minHeight:94,padding:13,borderRadius:16,borderWidth:1,borderColor:C.border,backgroundColor:C.card},kpiLabel:{color:C.soft,fontSize:10,textTransform:"uppercase",letterSpacing:.6},kpiValue:{color:C.text,fontWeight:"900",fontSize:21,marginTop:5},kpiMeta:{color:C.soft,fontSize:9,marginTop:4},card:{marginTop:12,padding:15,borderRadius:18,borderWidth:1,borderColor:C.border,backgroundColor:C.card},cardHead:{flexDirection:"row",justifyContent:"space-between",gap:10},cardTitle:{fontSize:14,fontWeight:"900",color:C.text},cardMeta:{fontSize:10,color:C.soft},categoryRow:{marginTop:12},categoryTop:{flexDirection:"row",justifyContent:"space-between",gap:10},categoryName:{color:C.text,fontSize:11,fontWeight:"700"},categoryValue:{color:C.soft,fontSize:10},bar:{height:5,borderRadius:99,backgroundColor:"rgba(255,255,255,.08)",overflow:"hidden",marginTop:6},fill:{height:"100%",borderRadius:99},moneyRow:{marginTop:11,paddingBottom:9,borderBottomWidth:1,borderBottomColor:"rgba(255,255,255,.06)",flexDirection:"row",justifyContent:"space-between"},note:{marginTop:10,color:C.soft,fontSize:9,lineHeight:14},sectionHead:{marginTop:22},sectionTitle:{fontSize:17,fontWeight:"900",color:C.text,marginTop:3},tx:{paddingVertical:12,borderBottomWidth:1,borderBottomColor:"rgba(255,255,255,.06)",flexDirection:"row",gap:12,alignItems:"center"},txTitle:{color:C.text,fontSize:12,fontWeight:"800"},txMeta:{color:C.soft,fontSize:9,marginTop:3,textTransform:"capitalize"},txAmounts:{alignItems:"flex-end"},txCredits:{color:C.text,fontSize:12,fontWeight:"900"},txMoney:{color:C.soft,fontSize:9,marginTop:2},empty:{paddingVertical:18,textAlign:"center",color:C.soft,fontSize:11},error:{marginTop:16,padding:14,borderRadius:14,backgroundColor:"rgba(255,90,100,.08)",borderWidth:1,borderColor:"rgba(255,90,100,.25)"},errorText:{color:C.red,fontSize:11}});
